leftnav:
- identifier: dcd09d0a-aa68-271a-cbbd-85c843ad7760
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 2a7ab027-dd4e-30b9-b09c-fe11446341ae
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: d07d4c63-af56-07ae-fe6c-aea9a8684067
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
- identifier: 43f286df-88a8-337c-5bfd-d7fb8d815aa8
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: 52d49917-1041-23ff-2845-a3cc926b18d1
  name: Projects
  url: /pages/projects
  weight: 50
- identifier: 73da280e-5997-0e20-c137-f9fbf6666ac9
  name: Related Resources
  url: /pages/related-resources
  weight: 60
